services:
  db:
    image: mysql:8.2.0
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql:Z
    ports:
      - "3306:3306"
  server:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src:Z
    depends_on:
      - db
    keep_usern: true
volumes:
  db-data:
