services:
  db:
    image: mysql:8.2.0
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql:Z
    ports:
      - "3306:3306"
    networks:
      - app-network
  server:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - app-network
volumes:
  db-data:
networks:
  app-network:
    driver: bridge
